# Generated by Django 5.1.2 on 2024-10-28 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oclock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30, verbose_name='Название группы')),
                ('student_quantity', models.IntegerField()),
                ('lesson_name', models.CharField(max_length=255)),
                ('teacher', models.CharField(max_length=255)),
                ('audience', models.IntegerField()),
                ('oclock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.oclock', verbose_name='Часы')),
                ('day_week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.week', verbose_name='День недели')),
            ],
        ),
    ]
