# Generated by Django 5.1.2 on 2024-10-28 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_oclock_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='day_week',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='lesson_name',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='oclock',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='week',
            name='title',
        ),
        migrations.AddField(
            model_name='week',
            name='day_name',
            field=models.CharField(default=1, max_length=15, verbose_name='День недели'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='blog.groups', verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groups',
            name='student_quantity',
            field=models.IntegerField(verbose_name='Количество студентов'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=255, verbose_name='Предмет')),
                ('teacher', models.CharField(max_length=255, verbose_name='Преподаватель')),
                ('oclock', models.TimeField(verbose_name='Время')),
                ('audience', models.IntegerField(verbose_name='Аудитория')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='blog.week', verbose_name='День недели')),
            ],
        ),
    ]
