# Generated by Django 5.1.2 on 2024-10-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_groups_audience_remove_groups_day_week_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oclock',
        ),
    ]
