# Generated by Django 5.1.2 on 2024-10-29 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_oclock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='group',
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='blog.groups', verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
