# Generated by Django 5.1.2 on 2024-12-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
