# Generated by Django 5.1.2 on 2024-12-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_schedulefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulefile',
            old_name='file',
            new_name='c1b11',
        ),
        migrations.AddField(
            model_name='schedulefile',
            name='c1b9',
            field=models.FileField(default=1, upload_to='schedules/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulefile',
            name='c2b11',
            field=models.FileField(default=1, upload_to='schedules/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulefile',
            name='c2b9',
            field=models.FileField(default=1, upload_to='schedules/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulefile',
            name='c3b9',
            field=models.FileField(default=1, upload_to='schedules/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulefile',
            name='it9',
            field=models.FileField(default=1, upload_to='schedules/'),
            preserve_default=False,
        ),
    ]
