# Generated by Django 5.1.2 on 2024-12-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_file_schedulefile_c1b11_schedulefile_c1b9_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulefile',
            old_name='c2b11',
            new_name='file',
        ),
    ]
