# Generated by Django 5.1.2 on 2024-12-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_c2b11_schedulefile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulefile',
            old_name='file',
            new_name='c2b11',
        ),
    ]
